#ordinary least squares

#homoscedastic the variance doesnt increase

#the residuals are normally distributed

#are additive instead of multiplicative

funciones vinculantes generalized linear models

gala is reference level

diferences in means 

y is the mean ciderph of the reference category gala

mean of the braeburn y de ahi se saca el slope

the first level of the factor 

a single straight line will connect to the means of the categories

en 2 si pero en 3 ni en 4!

k=4

we create k-1 dummy variables d1,d2,d3

GALA 000
BRAEBURN 100
Granny smidth 010
honey crisp 001

b0 + b1d1 + b2d2 + b3d3 + e

mean of the reference level Gala

al means 

por eso se hace asi para que siempre este una como referencia gala

y las otras se prenden y se apagan.

siempre necesitas 2 por eso apagas las otras!

4 - 1 slopes

In [10]:
library(mlr)
library(tidyverse)

In [12]:
data(Ozone, package = 'mlbench')

In [18]:
ozonetib<-as_tibble(Ozone)
ozonetib

    V1 V2 V3 V4 V5   V6 V7 V8 V9    V10  V11 V12   V13
1   1  1  4   3 5480 8  20 NA    NA 5000 -15 30.56 200
2   1  2  5   3 5660 6  NA 38    NA   NA -14    NA 300
3   1  3  6   3 5710 4  28 40    NA 2693 -25 47.66 250
4   1  4  7   5 5700 3  37 45    NA  590 -24 55.04 100
5   1  5  1   5 5760 3  51 54 45.32 1450  25 57.02  60
6   1  6  2   6 5720 4  69 35 49.64 1568  15 53.78  60
7   1  7  3   4 5790 6  19 45 46.40 2631 -33 54.14 100
8   1  8  4   4 5790 3  25 55 52.70  554 -28 64.76 250
9   1  9  5   6 5700 3  73 41 48.02 2083  23 52.52 120
10  1  10 6   7 5700 3  59 44    NA 2654  -2 48.38 120
11  1  11 7   4 5770 8  27 54    NA 5000 -19 48.56 120
12  1  12 1   6 5720 3  44 51 54.32  111   9 63.14 150
13  1  13 2   5 5760 6  33 51 57.56  492 -44 64.58  40
14  1  14 3   4 5780 6  19 54 56.12 5000 -44 56.30 200
15  1  15 4   4 5830 3  19 58 62.24 1249 -53 75.74 250
16  1  16 5   7 5870 2  19 61 64.94 5000 -67 65.48 200
17  1  17 6   5 5840 5  19 64    NA 5000 -40 63.32 200
18  1  18 7   9 5780 4  59 67    NA  639   1 66.02 150
19  1  19 1   4 5680 5  73 52 56.48  393 -68 69.80  10
20  1  20 2   3 5720 4  19 54    NA 5000 -66 54.68 140
21  1  21 3   4 5760 3  19 54 53.60 5000 -58 51.98 250
22  1  22 4   4 5730 4  26 58 52.70 5000 -26 51.98 200
23  1  23 5   5 5700 5  59 69 51.08 3044  18 52.88 150
24  1  24 6   6 5650 5  70 51    NA 3641  23 47.66 140
25  1  25 7   9 5680 3  64 53    NA  111 -10 59.54  50
26  1  26 1   5 5780 3  NA 56 53.60  692 -25 67.10   0
27  1  27 2   6 5820 5  19 59 59.36  597 -52 70.52  70
28  1  28 3   6 5830 4  NA 59 60.08   NA -44    NA 150
29  1  29 4   6 5810 5  19 64 56.66 1791 -15 64.76 150
30  1  30 5  11 5790 3  28 63 57.38  793 -15 65.84 120
⋮   ⋮  ⋮  ⋮  ⋮  ⋮    ⋮  ⋮  ⋮  ⋮     ⋮    ⋮   ⋮     ⋮
337 12 2  4  3  5870 3  19 53 60.80 3720 -50 61.34 200
338 12 3  5  3  5830 2  27 58 59.00  311 -24 69.98 200
339 12 4  6  6  5760 0  64 55    NA 2536  28 56.48  80
340 12 5  7  6  5680 0  52 50    NA 1154 -22 61.52  60
341 12 6  1  5  5780 4  19 48 54.14 2933 -40 59.90 300
342 12 7  2  3  5810 3  19 51 58.28 3064 -33 62.78 200
343 12 8  3  4  5760 0  32 62 56.12  826 -16 64.76 300
344 12 9  4  7  5680 0  58 40 46.94 5000   2 42.98  50
345 12 10 5  5  5750 0  26 44 52.88  111 -52 68.18  40
346 12 11 6  5  5790 5  19 49    NA 5000 -48 54.68  70
347 12 12 7  4  5770 3  19 53    NA 5000 -37 55.58 150
348 12 13 1  3  5750 0  19 53 51.98 5000 -26 51.08 150
349 12 14 2  2  5720 0  19 53 52.70 5000 -31 51.44  70
350 12 15 3  5  5760 3  19 55 58.10  948 -48 70.70 200
351 12 16 4  3  5780 0  19 51 54.32 5000 -50 50.90 120
352 12 17 5  4  5660 4  19 54 49.64 5000 -22 48.56 150
353 12 18 6  4  5610 2  58 48    NA 3687 -10 46.94 150
354 12 19 7  6  5640 0  51 53    NA 5000   0 44.24  60
355 12 20 1  6  5680 3  52 49 48.38 5000 -19 45.68  70
356 12 21 2  3  5650 5  19 48 47.12 5000 -28 45.32 150
357 12 22 3  4  5710 4  19 51 51.08 5000 -25 48.38 300
358 12 23 4  3  5680 4  57 47 45.32  508 -10 58.64 100
359 12 24 5  8  5630 4  50 50    NA 2851  -5 50.00  70
360 12 25 6  5  5770 0  NA 49    NA   NA -35    NA  40
361 12 26 7  3  5800 7  19 51    NA 3143  NA 60.26 140
362 12 27 1  2  5730 3  53 51 49.28  111 -14 72.50 200
363 12 28 2  3  5690 3  23 51 49.28 5000 -36 51.26  70
364 12 29 3  5  5650 3  61 50 46.58 3704  18 46.94  40
365 12 30 4  1  5550 4  85 39 41.00 5000   8 39.92 100
366 12 31 5  2    NA 4  68 37    NA 5000  -3 37.22  70

[1] "Month"

In [36]:
names(ozonetib)<-c(
    'Month',
    'Date',
    'Day',
    'Ozone',
    'Press_height',
    'Wind',
    'Humid',
    'Temp_Sand',
    'Temp_Monte',
    'Inv_height',
    'Press_grad',
    'Inv_temp',
    'Visib'
)

In [37]:
ozonetib

    Month Date Day Ozone Press_height Wind Humid Temp_Sand Temp_Monte
1   1     1    4    3    5480         8    20    NA           NA
2   1     2    5    3    5660         6    NA    38           NA
3   1     3    6    3    5710         4    28    40           NA
4   1     4    7    5    5700         3    37    45           NA
5   1     5    1    5    5760         3    51    54        45.32
6   1     6    2    6    5720         4    69    35        49.64
7   1     7    3    4    5790         6    19    45        46.40
8   1     8    4    4    5790         3    25    55        52.70
9   1     9    5    6    5700         3    73    41        48.02
10  1     10   6    7    5700         3    59    44           NA
11  1     11   7    4    5770         8    27    54           NA
12  1     12   1    6    5720         3    44    51        54.32
13  1     13   2    5    5760         6    33    51        57.56
14  1     14   3    4    5780         6    19    54        56.12
15  1     15   4    4    5830         3    19    58        62.24
16  1     16   5    7    5870         2    19    61        64.94
17  1     17   6    5    5840         5    19    64           NA
18  1     18   7    9    5780         4    59    67           NA
19  1     19   1    4    5680         5    73    52        56.48
20  1     20   2    3    5720         4    19    54           NA
21  1     21   3    4    5760         3    19    54        53.60
22  1     22   4    4    5730         4    26    58        52.70
23  1     23   5    5    5700         5    59    69        51.08
24  1     24   6    6    5650         5    70    51           NA
25  1     25   7    9    5680         3    64    53           NA
26  1     26   1    5    5780         3    NA    56        53.60
27  1     27   2    6    5820         5    19    59        59.36
28  1     28   3    6    5830         4    NA    59        60.08
29  1     29   4    6    5810         5    19    64        56.66
30  1     30   5   11    5790         3    28    63        57.38
⋮   ⋮     ⋮    ⋮   ⋮     ⋮            ⋮    ⋮     ⋮         ⋮
337 12    2    4   3     5870         3    19    53        60.80
338 12    3    5   3     5830         2    27    58        59.00
339 12    4    6   6     5760         0    64    55           NA
340 12    5    7   6     5680         0    52    50           NA
341 12    6    1   5     5780         4    19    48        54.14
342 12    7    2   3     5810         3    19    51        58.28
343 12    8    3   4     5760         0    32    62        56.12
344 12    9    4   7     5680         0    58    40        46.94
345 12    10   5   5     5750         0    26    44        52.88
346 12    11   6   5     5790         5    19    49           NA
347 12    12   7   4     5770         3    19    53           NA
348 12    13   1   3     5750         0    19    53        51.98
349 12    14   2   2     5720         0    19    53        52.70
350 12    15   3   5     5760         3    19    55        58.10
351 12    16   4   3     5780         0    19    51        54.32
352 12    17   5   4     5660         4    19    54        49.64
353 12    18   6   4     5610         2    58    48           NA
354 12    19   7   6     5640         0    51    53           NA
355 12    20   1   6     5680         3    52    49        48.38
356 12    21   2   3     5650         5    19    48        47.12
357 12    22   3   4     5710         4    19    51        51.08
358 12    23   4   3     5680         4    57    47        45.32
359 12    24   5   8     5630         4    50    50           NA
360 12    25   6   5     5770         0    NA    49           NA
361 12    26   7   3     5800         7    19    51           NA
362 12    27   1   2     5730         3    53    51        49.28
363 12    28   2   3     5690         3    23    51        49.28
364 12    29   3   5     5650         3    61    50        46.58
365 12    30   4   1     5550         4    85    39        41.00
366 12    31   5   2       NA         4    68    37           NA
    Inv_height Press_grad Inv_temp Visib
1   5000       -15        30.56    200
2     NA       -14           NA    300
3   2693       -25        47.66    250
4    590       -24        55.04    100
5   1450        25        57.02     60
6   1568        15        53.78     60
7   2631       -33        54.14    100
8    554       -28        64.76    250
9   2083        23        52.52    120
10  2654        -2        48.38    120
11  5000       -19        48.56    120
12   111         9        63.14    150
13   492       -44        64.58     40
14  5000       -44        56.30    200
15  1249       -53        75.74    250
16  5000       -67        65.48    200
17  5000       -40        63.32    200
18   639         1        66.02    150
19   393       -68        69.80     10
20  5000       -66        54.68    140
21  5000       -58        51.98    250
22  5000       -26        51.98    200
23  3044        18        52.88    150
24  3641        23        47.66    140
25   111       -10        59.54     50
26   692       -25        67.10      0
27   597       -52        70.52     70
28    NA       -44           NA    150
29  1791       -15        64.76    150
30   793       -15        65.84    120
⋮   ⋮          ⋮          ⋮        ⋮
337 3720       -50        61.34    200
338  311       -24        69.98    200
339 2536        28        56.48     80
340 1154       -22        61.52     60
341 2933       -40        59.90    300
342 3064       -33        62.78    200
343  826       -16        64.76    300
344 5000         2        42.98     50
345  111       -52        68.18     40
346 5000       -48        54.68     70
347 5000       -37        55.58    150
348 5000       -26        51.08    150
349 5000       -31        51.44     70
350  948       -48        70.70    200
351 5000       -50        50.90    120
352 5000       -22        48.56    150
353 3687       -10        46.94    150
354 5000         0        44.24     60
355 5000       -19        45.68     70
356 5000       -28        45.32    150
357 5000       -25        48.38    300
358  508       -10        58.64    100
359 2851        -5        50.00     70
360   NA       -35           NA     40
361 3143        NA        60.26    140
362  111       -14        72.50    200
363 5000       -36        51.26     70
364 3704        18        46.94     40
365 5000         8        39.92    100
366 5000        -3        37.22     70